name: Snyk scan
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
jobs:
  security:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Snyk Node CLI
        run: npm install -g snyk
      - name: Test for vulnerabilities
        if: ${{ github.event_name == 'pull_request' }}
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --org=kiali --prune-repeated-subdependencies
      - name: Take Snyk snapshot
        if: ${{ github.event_name == 'push' }}
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --org=kiali --prune-repeated-subdependencies
